### ISSUE TITLE
Could not set unknown property 'domainServerGroup'

### ISSUE THREAD

**Issue by vipivoxa** [Ingwersaft/wildfly-deploy-gradle-plugin#23]
Hi,
Trying to deploy to a domain server group,
getting the following error:  
Could not set unknown property 'domainServerGroup' for task ':deployDomain' of type com.mkring.wildlydeplyplugin.DeployWildflyTask.

is a server group deployment supported like it is described in a readme?

**Comment by Ingwersaft** [comment]
Mhm, this was contributed by #20 , never used it myself.

`Could not set unknown property` sound's like you're running an old version of the plugin, which version are you using?

**Comment by vipivoxa** [comment]
used the one what is mentioned in the current readme.md example:
 
`id "com.mkring.wildlydeplyplugin.deploy-wildfly-plugin" version "0.2.10"`

and

```
task deployDomain(type: DeployWildflyTask) {

    host = project.findProperty("deployHost")
    port = Integer.parseInt(project.findProperty("deployPort"))
    user = project.findProperty("deployUser")
    password =  project.findProperty("deployPwd")
    deploymentName = project.name
    runtimeName = "test-1"
    file = "build/libs/${rootProject.name}-${version}.war"
    // redeploy if artifact with same name already deployed
    undeployBeforehand = true
    // server group of domain mode
    domainServerGroup = "test-server-group"
    // ask to restart servers after deploy instead of only reload them
    restart = true
    reload = false
}
```

**Comment by Ingwersaft** [comment]
The readme isn't updated, use the latest version from the gradle plugins portal

**Comment by vipivoxa** [comment]
thanks! worked with a version '0.3.0' and a minimum gradle version 5. 
though with some repeatable warn messages about cli cfg not found, 

`$ ./gradlew deployDomain
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

> Task :deployDomain
WARN: can't find jboss-cli.xml. Using default configuration values.
WARN: can't find jboss-cli.xml. Using default configuration values.

BUILD SUCCESSFUL in 5s
1 actionable task: 1 executed`
